<img src=https://1.bp.blogspot.com/-CHMzy5L0Qcw/Wpy00BAw-dI/AAAAAAAAG9g/fBinxajEzcshsZPSemZIt37JlqOWdDWbQCLcBGAs/s1600/numpy.jpeg width=300>

<img src=https://slideplayer.com/slide/15975727/88/images/3/What+is+NumPy+NumPy+is+the+fundamental+package+needed+for+scientific+computing+with+Python.+It+contains%3A.jpg width=400>

# Importing Libraries

In [1]:
#importing numpy library
import numpy as np

---
---

# Creating numpy array

In [2]:
#How to form a 1D array
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
#How to form a 2D array
y=np.array([(1,2,3,4),(5,6,7,8)])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


---
---

# List VS numpy array

In [14]:
import time
import sys

In [15]:
#Mem occupied by numpy array is way less than Mem occupied by list
S=range(1000)
print("Mem occupied by list: ",sys.getsizeof(5)*len(S))
D=np.arange(1000)
print("Mem occupied by numpy array: ",D.size*D.itemsize)

Mem occupied by list:  28000
Mem occupied by numpy array:  4000


In [17]:
#numpy array is faster than list

SIZE=1000000

L1=range(SIZE)
L2=range(SIZE)

start=time.time()
result=[(x,y) for x,y in zip(L1,L2)]

print("time taken by list is:",(time.time()-start)*1000)


A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=A1+A2

print("time taken by numpy array is:",(time.time()-start)*1000)


time taken by list is: 181.73837661743164
time taken by numpy array is: 78.11427116394043


---
---

# Operations in Numpy

In [7]:
a=np.array([(1,2,3,6),(4,5,6,8)])
print(a)
print("dimension of array is: ",a.ndim)
print("each element takes size of(bytes): ",a.itemsize)
print("datatype of array is: ",a.dtype)
print("number of elements in array: ",a.size)
print("shape  of array is: ",a.shape)

[[1 2 3 6]
 [4 5 6 8]]
dimension of array is:  2
each element takes size of(bytes):  4
datatype of array is:  int32
number of elements in array:  8
shape  of array is:  (2, 4)


In [8]:
#How to reshape a numpy array
a=a.reshape(4,2)#This changes the array with shape (2,4) into (4,2)
print(a)

[[1 2]
 [3 6]
 [4 5]
 [6 8]]


In [9]:
#How to slice a numpy array
x=np.array([(11,12,13,14),(15,16,17,18),(19,20,21,22)])
print(x)
print('-'*20)

#accessing an entry in a numpy array
print(x[0,3])#third index of zero row

#condition on columns
print(x[:,3])#third column from all rows

#condition on rows
print(x[2 ,:])

#condition on both rows and columns
print(x[1:,2:])

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
--------------------
14
[14 18 22]
[19 20 21 22]
[[17 18]
 [21 22]]


In [10]:
#Creating a numpy array of random numbers(with range)

#creating a random array of 10 numbers between 1 and 1000(1-inclusive 1000-exclusive)
a=np.array(np.random.randint(1,1000,10)) #np.random.randint(start,end,count)
print(a)

[852 761 191 108 778 464 468 522  64 285]


In [11]:
#Creating a numpy array of random numbers(no range,parameters=shape)
a=np.random.rand(5,5)
print(a)

[[0.8576646  0.42308876 0.74690109 0.19368873 0.86186668]
 [0.13855663 0.66738604 0.03646788 0.41723626 0.83130786]
 [0.18464519 0.74554261 0.16070016 0.70718619 0.89936685]
 [0.35323943 0.42463693 0.44078428 0.0068995  0.34567637]
 [0.71081967 0.42719409 0.41410521 0.88092116 0.77571273]]


In [12]:
#How to append an element to a numpy array
a=np.append(a,[3])
print(a)

[0.8576646  0.42308876 0.74690109 0.19368873 0.86186668 0.13855663
 0.66738604 0.03646788 0.41723626 0.83130786 0.18464519 0.74554261
 0.16070016 0.70718619 0.89936685 0.35323943 0.42463693 0.44078428
 0.0068995  0.34567637 0.71081967 0.42719409 0.41410521 0.88092116
 0.77571273 3.        ]


In [18]:
#shortcut to creating a numpy array containing numbers from 1 to 10(1-inclusive 10-exclusive)
x=np.array(list(range(10))) #np.array(list(range(n)))
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#shortcut to creating a numpy array containing numbers between 1 to 10(1-inclusive 10-exclusive) in gaps of 2
# arbitrary start, stop and step 
x=np.array(np.arange(1,10,2)) #np.arange(start,end,gap)
print(x)

[1 3 5 7 9]


In [20]:
#How to change the datatype of a numpy array
#integer array to float in this case
#dtype can be =np.float/np.int/np.complex
x=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float)
x

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [21]:
#Another way to change the datatype of a numpy array -array.astype()
#integer32 to complex128 in this case
arr =np.array([[1,2,3,4],[5,6,7,8]])
print("datatype of original array :",arr.dtype)
arr = arr.astype('complex128')
print("datatype of converted array :",arr.dtype)
print(arr)

datatype of original array : int32
datatype of converted array : complex128
[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 7.+0.j 8.+0.j]]


In [22]:
x

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [23]:
#There are many mathematical built-in functions in numpy.Some of them are mentioned below:

print("mean of the elements of an array :",np.mean(x))
print("median of the elements of an array :",np.median(x))
print("sum of the elements of an array :",np.sum(x))
print("minimum of the element of an array : ",np.min(x))
print("maximum of the elements of an array :",np.max(x))
print("element-wise square root :",np.sqrt(x))
print("standard deviation of an array :",np.std(x))
print("transpose of an array :" ,x.transpose())

mean of the elements of an array : 4.5
median of the elements of an array : 4.5
sum of the elements of an array : 36.0
minimum of the element of an array :  1.0
maximum of the elements of an array : 8.0
element-wise square root : [[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
standard deviation of an array : 2.29128784747792
transpose of an array : [[1. 5.]
 [2. 6.]
 [3. 7.]
 [4. 8.]]


In [24]:
#creating a grid of numbers
x,y= np.mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [25]:
#creating an array of ones

#shape of (1,10)
print(np.ones(10))
print('-'*50)

#shape of (3,3)
print(np.ones((3,3)))
print('-'*50)

#creating an array of zeros

#shape of (1,10)
print(np.zeros(10))
print('-'*50)

#shape of (3,3)
print(np.zeros((3,3)))
print('-'*50)

#creating an identity array
print(np.eye(2))  
print('-'*50)

#creating a diagonal array
print(np.diag([1,2,3]))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
--------------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
--------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
[[1. 0.]
 [0. 1.]]
--------------------------------------------------
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [26]:
#10 equally spaced values b/w 1 and 3(1 and 3-inclusive)
#OR
# Creating 10 ticks between 1 and 3
np.linspace(1,3,10) #np.linespace(start,end,no. of values)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [27]:
#addition in a numpy array
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('-'*10)
print(a.sum(axis=0)) #column-wise addition of elements
print(a.sum(axis=1)) #row-wise addition of elements

[[1 2 3]
 [4 5 6]]
----------
[5 7 9]
[ 6 15]


In [28]:
#addition of two arrays element-wise
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(7,8,9),(10,11,12)])
print(a+b)

[[ 8 10 12]
 [14 16 18]]


In [29]:
#subtraction of two arrays element-wise
print(a-b)

[[-6 -6 -6]
 [-6 -6 -6]]


In [30]:
#multiplication of two arrays element-wise
print(a*b)

[[ 7 16 27]
 [40 55 72]]


In [31]:
#division of two arrays element-wise
print(a/b)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [32]:
#How to append two arrays vertically
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('-'*10)
b=np.array([(7,8,9),(10,11,12)])
print(b)
print('-'*10)

print(np.vstack((a,b))) #np.vstack(array1,array2)

[[1 2 3]
 [4 5 6]]
----------
[[ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
#How to append two arrays horizontally
print(np.hstack((a,b))) #np.hstack(array1,array2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


---
---

# Things to remember

In [34]:
# arrays keep their type even if elements changed 
d = np.arange(5) 
print(d.dtype)
d[1] = 9.7
print(d.dtype)   

int32
int32


In [35]:
# operations create a new array, with new type
x=d*0.4
print(x)
print(x.dtype)

[0.  3.6 0.8 1.2 1.6]
float64


In [36]:
#Two ndarrays are mutable and may be views to the same memory

#Try avoiding this because if you change x,y will also be changed
x = np.array([1,2,3,4])
y=x
print(x is y)
print(id(x), id(y))
x[0]=9
print(x)
print(y)

print('-'*50)
#This is a good approach-always use this!!
x = np.array([1,2,3,4])
y = x.copy()
print(x is y)
print(id(x), id(y))
x[0]=9
print(x)
print(y)

True
2297338234480 2297338234480
[9 2 3 4]
[9 2 3 4]
--------------------------------------------------
False
2297338448352 2297338234240
[9 2 3 4]
[1 2 3 4]


In [37]:
# can use integer lists as indices 
arr = np.arange(100, 200)
select = [5, 25, 50, 75, -5]
print(arr[select]) 

[105 125 150 175 195]


In [38]:
arr = np.arange(10, 20 )
div_by_3 = arr%3 == 0 # comparison produces boolean array
print(div_by_3)
print(arr[div_by_3]) # can use boolean lists as indices

[False False  True False False  True False False  True False]
[12 15 18]


In [39]:
print(div_by_3.all())#logical "and" operation
print(div_by_3.any())#logical "or" operation
print(div_by_3.sum())#number of true values
print(div_by_3.nonzero())#index of true values

False
True
3
(array([2, 5, 8], dtype=int64),)


In [40]:
# Sorting an array

# array.sort() -->acts on array itself
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort()
print(arr) 
print('-'*50)

# np.sort(array) -->does not act on array itself
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
print(np.sort(x))
print(x)

[1.2 1.8 2.3 4.5 5.5 6.7]
--------------------------------------------------
[1.2 1.8 2.3 4.5 5.5 6.7]
[4.5 2.3 6.7 1.2 1.8 5.5]
